### ISSUE TITLE
Updating to esp32 1.0.6 or 2.0.x?

### ISSUE THREAD

**Issue by dwightkelly** [openmrn/OpenMRNLite#4]
Has any work been done to update to esp32 1.0.6 or 2.0.x releases?

**Comment by balazsracz** [comment]
yes, there is a branch here: https://github.com/bakerstu/openmrn/pull/536
if you check out that branch you can create an openmrnlite using the instructions here: https://github.com/bakerstu/openmrn/blob/master/arduino/RELEASE.md

**Comment by atanisoft** [comment]
This should now be working with the 2.0.0 release of OpenMRNLite.
